from typing import Dict, Any, List

def generate_research_report(project: Dict[str, Any], dataset_report: Dict[str, Any], baselines: List[Dict[str, Any]], tree_nodes: List[Dict[str, Any]], error_analysis: Dict[str, Any]) -> str:
    """
    Generates a full Markdown research report for the autonomous ML pipeline.
    Complies with Sakana AI License Clause 3.2.e machine-generated content disclosure requirements.
    """
    objective = project.get("objective", "Not specified")
    dataset_name = project.get("datasetName", "Not selected")
    best_model = project.get("bestModel", "Not trained")
    best_metric = project.get("bestMetric", "N/A")

    report_lines = [
        f"# Autonomous ML Research Report: {project.get('name', 'Research Project')}",
        "",
        "> **DISCLOSURE (Sakana AI License Clause 3.2.e):** This report was automatically machine-generated by the AutoML Scientist autonomous research system.",
        "",
        "## 1. Executive Summary",
        f"- **Research Objective**: {objective}",
        f"- **Primary Dataset**: `{dataset_name}`",
        f"- **Best Model Architecture**: `{best_model}`",
        f"- **Top Validation Performance**: `{best_metric}`",
        f"- **Total Experiments Completed**: {len(tree_nodes)}",
        "",
        "## 2. Dataset Analysis & EDA",
    ]

    if dataset_report:
        report_lines.extend([
            f"- **Filename**: `{dataset_report.get('filename')}`",
            f"- **Rows**: {dataset_report.get('rowCount'):,} | **Columns**: {dataset_report.get('columnCount')}",
            f"- **Target Column**: `{dataset_report.get('targetCandidate')}` ({dataset_report.get('taskType')})",
            f"- **Missing Values**: {dataset_report.get('missingValuesTotal')} cells",
            f"- **Duplicate Rows**: {dataset_report.get('duplicateRows')}",
            "",
            "### Detected Data Issues:",
        ])
        for issue in dataset_report.get("detectedIssues", []):
            report_lines.append(f"- **[{issue.get('severity')}] {issue.get('title')}**: {issue.get('desc')}")
    else:
        report_lines.append("No dataset analysis available.")

    report_lines.extend([
        "",
        "## 3. Baseline Model Benchmarks",
        "| Model Name | Model Type | Metric | Runtime | Status |",
        "| --- | --- | --- | --- | --- |"
    ])

    for b in baselines:
        metrics_str = ", ".join([f"{k.upper()}: {v}" for k, v in b.get("metrics", {}).items()])
        report_lines.append(f"| {b.get('name')} | {b.get('type')} | {metrics_str} | {b.get('trainingTime')} | {b.get('status')} |")

    report_lines.extend([
        "",
        "## 4. Autonomous Experimentation Tree",
    ])

    for node in tree_nodes:
        report_lines.extend([
            f"### Node: {node.get('title')}",
            f"- **Hypothesis**: {node.get('hypothesis')}",
            f"- **Status**: `{node.get('status')}` ({node.get('metricName', 'Metric')}: {node.get('metricValue')})",
            f"- **Configuration**: `{node.get('hyperparams')}`",
            f"- **Execution Time**: {node.get('executionTime')}",
            ""
        ])

    report_lines.extend([
        "## 5. Error Analysis & Key Takeaways",
    ])

    if error_analysis:
        report_lines.extend([
            f"- **False Positives**: {error_analysis.get('falsePositivesCount')}",
            f"- **False Negatives**: {error_analysis.get('falseNegativesCount')}",
            f"- **Diagnosis**: {error_analysis.get('failureDiagnosis')}",
            ""
        ])

    report_lines.extend([
        "## 6. Recommendations & Next Steps",
        "1. Deploy the best performing pipeline configuration into production serving.",
        "2. Monitor real-world data drift on key failing feature signatures identified in error analysis.",
        "3. Collect further edge-case training samples for underperforming data slices."
    ])

    return "\n".join(report_lines)
