import React from 'react';
import { FileText, Download, ShieldCheck, CheckCircle2, Award, AlertOctagon, Sparkles } from 'lucide-react';

export default function ReportView() {
  const handleDownload = (format) => {
    alert(`Downloading Final Research Report in ${format} format...`);
  };

  return (
    <div className="p-8 space-y-8 max-w-5xl mx-auto">
      {/* Header and Download bar */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 border-b border-slate-800 pb-6">
        <div>
          <div className="inline-flex items-center space-x-2 bg-emerald-500/10 border border-emerald-500/30 px-3 py-1 rounded-full text-xs font-mono text-emerald-300 mb-2">
            <FileText className="w-3.5 h-3.5" />
            <span>Autonomous ML Research Report</span>
          </div>
          <h2 className="text-2xl font-extrabold text-white tracking-tight">
            Final Research Report: Fraud Detection Optimization
          </h2>
          <p className="text-xs text-slate-400 font-mono mt-1">
            Generated by AutoML Scientist • Session ID: exp-fraud-2026-0917
          </p>
        </div>

        <div className="flex items-center space-x-3">
          <button
            onClick={() => handleDownload('PDF')}
            className="px-4 py-2 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-white font-bold text-xs shadow-md shadow-cyan-500/20 flex items-center space-x-2"
          >
            <Download className="w-4 h-4" />
            <span>Export PDF</span>
          </button>
          <button
            onClick={() => handleDownload('Markdown')}
            className="px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 text-xs font-semibold"
          >
            Markdown
          </button>
          <button
            onClick={() => handleDownload('JSON')}
            className="px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 text-xs font-semibold"
          >
            JSON Record
          </button>
        </div>
      </div>

      {/* Report Document Content */}
      <div className="glass-panel p-10 rounded-2xl border border-slate-800 space-y-8 bg-slate-900/90 text-slate-200 font-sans leading-relaxed">
        {/* Title Block */}
        <div className="text-center space-y-3 border-b border-slate-800 pb-8">
          <h1 className="text-2xl font-extrabold text-white tracking-tight">
            Autonomous Optimization of Credit Card Fraud Detection Under Extreme Class Imbalance
          </h1>
          <p className="text-xs text-cyan-400 font-mono">
            AutoML Scientist Platform • Experiment Tree Branch #01.1
          </p>
        </div>

        {/* Abstract */}
        <div className="space-y-2 bg-slate-950/60 p-5 rounded-xl border border-slate-800">
          <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider font-mono">Abstract</h3>
          <p className="text-xs text-slate-300 leading-relaxed">
            We present an autonomous machine learning discovery pipeline for credit card fraud detection under severe positive class prevalence (0.17%). Utilizing gradient boosted decision trees combined with dynamic positive class weight calibration (scale_pos_weight = 577.8) and post-hoc classification threshold optimization at 0.34, AutoML Scientist increased Precision-Recall AUC (PR-AUC) from a baseline of 0.841 to 0.884 (+24.1% relative improvement over standard baselines). Statistical hypothesis testing confirmed p-value = 0.0034 (p &lt; 0.01).
          </p>
        </div>

        {/* Section 1: Research Question & Motivation */}
        <div className="space-y-3">
          <h3 className="text-base font-bold text-white tracking-tight font-mono text-cyan-300">
            1. Research Question & Motivation
          </h3>
          <p className="text-xs text-slate-300">
            Financial fraud detection systems operate in extreme imbalanced environments where false negatives result in unrecoverable financial loss, while excessive false positives exhaust human audit capacity. This research investigated whether dynamic loss-scaling and decision threshold tuning outperform traditional synthetic oversampling techniques (SMOTE).
          </p>
        </div>

        {/* Section 2: Dataset Profile & Baselines */}
        <div className="space-y-3">
          <h3 className="text-base font-bold text-white tracking-tight font-mono text-cyan-300">
            2. Dataset Profiling & Baseline Benchmarks
          </h3>
          <p className="text-xs text-slate-300">
            The target dataset consists of 284,807 transaction records with 30 anonymized PCA features. Profiling revealed 492 positive fraud cases (0.17%). Baseline evaluation yielded:
          </p>
          <ul className="list-disc list-inside text-xs text-slate-300 space-y-1 font-mono">
            <li>Logistic Regression: PR-AUC 0.712, F1 0.694</li>
            <li>Random Forest (200 trees): PR-AUC 0.825, F1 0.814</li>
            <li>Raw XGBoost Baseline: PR-AUC 0.841, F1 0.835</li>
          </ul>
        </div>

        {/* Section 3: Hypotheses & Sandbox Experimentation */}
        <div className="space-y-3">
          <h3 className="text-base font-bold text-white tracking-tight font-mono text-cyan-300">
            3. Hypotheses & Sandbox Experimentation
          </h3>
          <p className="text-xs text-slate-300">
            AutoML Scientist formulated 4 distinct hypotheses executed inside isolated Docker containers:
          </p>
          <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 space-y-2 text-xs font-mono">
            <div className="text-emerald-400 font-bold">Hypothesis 1.1 (WINNER):</div>
            <p className="text-slate-300 font-sans">
              Adjusting class weighting scale_pos_weight=577.8 coupled with decision threshold optimization at 0.34 shifts prediction boundary away from true negative dominance, yielding PR-AUC 0.884 and Recall 0.880.
            </p>
          </div>
        </div>

        {/* Section 4: Error & Statistical Analysis */}
        <div className="space-y-3">
          <h3 className="text-base font-bold text-white tracking-tight font-mono text-cyan-300">
            4. Error Decomposition & Statistical Significance
          </h3>
          <p className="text-xs text-slate-300">
            Post-hoc error analysis identified 38 false positives and 42 false negatives. Stealth micro-transactions (&lt; $10.00) accounted for 61.9% of false negatives due to feature signature overlap with legitimate retail purchases. Paired t-test across 5 random seeds confirmed p-value = 0.0034.
          </p>
        </div>

        {/* MANDATORY AI DISCLOSURE NOTICE */}
        <div className="p-6 rounded-xl bg-cyan-950/40 border border-cyan-500/40 space-y-2">
          <div className="flex items-center space-x-2 text-cyan-400 text-xs font-mono font-bold uppercase">
            <ShieldCheck className="w-4 h-4 text-emerald-400" />
            <span>MANDATORY AI-GENERATED RESEARCH DISCLOSURE</span>
          </div>
          <p className="text-xs text-slate-200 leading-relaxed font-mono">
            &quot;This document and the underlying experimental findings were autonomously produced using AutoML Scientist, a platform derived from and inspired by Sakana AI&apos;s The AI Scientist (https://github.com/SakanaAI/AI-Scientist-v2).&quot;
          </p>
        </div>
      </div>
    </div>
  );
}
