import React, { useState, useEffect } from 'react';
import { FileText, Download, ShieldCheck, Loader2 } from 'lucide-react';
import { fetchProjectReport } from '../api';

export default function ReportView({ activeProject }) {
  const [reportMd, setReportMd] = useState('');
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!activeProject?.id) return;
    setLoading(true);
    fetchProjectReport(activeProject.id).then((data) => {
      setReportMd(data);
      setLoading(false);
    });
  }, [activeProject?.id]);

  const handleDownload = (format) => {
    const element = document.createElement("a");
    const file = new Blob([reportMd], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `research_report_${activeProject?.id || 'export'}.md`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  if (!activeProject) {
    return (
      <div className="p-8 max-w-7xl mx-auto">
        <div className="glass-panel p-12 rounded-xl text-center space-y-3 border-slate-800">
          <FileText className="w-10 h-10 text-slate-600 mx-auto" />
          <h3 className="text-lg font-bold text-slate-200 font-mono">Not configured</h3>
          <p className="text-xs text-slate-400">Select or start a research project to view the generated research report.</p>
        </div>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="p-8 max-w-7xl mx-auto flex items-center justify-center min-h-[400px]">
        <div className="flex items-center space-x-3 text-emerald-400 font-mono text-sm">
          <Loader2 className="w-6 h-6 animate-spin" />
          <span>Generating comprehensive research report...</span>
        </div>
      </div>
    );
  }

  return (
    <div className="p-8 space-y-8 max-w-5xl mx-auto">
      {/* Header and Download bar */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 border-b border-slate-800 pb-6">
        <div>
          <div className="inline-flex items-center space-x-2 bg-emerald-500/10 border border-emerald-500/30 px-3 py-1 rounded-full text-xs font-mono text-emerald-300 mb-2">
            <FileText className="w-3.5 h-3.5" />
            <span>Autonomous ML Research Report</span>
          </div>
          <h2 className="text-2xl font-extrabold text-white tracking-tight">
            Research Report: {activeProject.name}
          </h2>
          <p className="text-xs text-slate-400 font-mono mt-1">
            Generated by AutoML Scientist • Session ID: {activeProject.id}
          </p>
        </div>

        <div className="flex items-center space-x-3">
          <button
            onClick={() => handleDownload('Markdown')}
            className="px-4 py-2 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-white font-bold text-xs shadow-md shadow-cyan-500/20 flex items-center space-x-2 cursor-pointer"
          >
            <Download className="w-4 h-4" />
            <span>Export Report (.md)</span>
          </button>
        </div>
      </div>

      {/* Report Document Content */}
      <div className="glass-panel p-10 rounded-2xl border border-slate-800 space-y-8 bg-slate-900/90 text-slate-200 font-sans leading-relaxed">
        <div className="prose prose-invert max-w-none text-xs font-mono whitespace-pre-wrap">
          {reportMd || "No research report generated yet."}
        </div>

        {/* MANDATORY AI DISCLOSURE NOTICE */}
        <div className="p-6 rounded-xl bg-cyan-950/40 border border-cyan-500/40 space-y-2 mt-8">
          <div className="flex items-center space-x-2 text-cyan-400 text-xs font-mono font-bold uppercase">
            <ShieldCheck className="w-4 h-4 text-emerald-400" />
            <span>MANDATORY AI-GENERATED RESEARCH DISCLOSURE</span>
          </div>
          <p className="text-xs text-slate-200 leading-relaxed font-mono">
            &quot;This document and the underlying experimental findings were machine-generated using AutoML Scientist, an original ML-focused autonomous research platform inspired by Sakana AI&apos;s AI Scientist-v2 (https://github.com/SakanaAI/AI-Scientist-v2).&quot;
          </p>
        </div>
      </div>
    </div>
  );
}
